### ISSUE TITLE
ruby torquebox site is redirecting to a spam gambling site

### ISSUE THREAD

**Issue by sayleenaik** [jruby/jruby-maven-plugins#135]
https://rubygems-proxy.torquebox.org/ is getting redirected to https://kes-krasnogorsk.ru/

<img width="1704" alt="image" src="https://github.com/jruby/jruby-maven-plugins/assets/16734993/ca1a8b37-e0fa-4416-9d41-d876c630e5f1">
And this seems like this site has been hacked.

**Comment by sayleenaik** [comment]
@mkristian ☝️

**Comment by headius** [comment]
We can't really do anything about this domain anymore because we don't own it now and we didn't actually own it before (developers of Torquebox or Red Hat itself owned the domain).

The rubygems proxy server has been deprecated for many years, and there are alternatives available (like the mavengem plugin) that make it obsolete and unnecessary.
